version: '3.3'

services:
  app:
    image: v4dikos/shelter:latest
    container_name: bunker-app
    ports:
      - "8723:8723"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: bunker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
